# Generated by Django 4.2.28 on 2026-02-14 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailylog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="dailylog",
            index=models.Index(
                fields=["user", "date"], name="idx_daily_logs_user_date"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailylog",
            unique_together={("user", "date")},
        ),
    ]
