# Generated by Django 4.2.28 on 2026-02-25 18:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("logs", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomMetricDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("unit", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "custom_metric_definitions",
                "ordering": ["name"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.RemoveField(
            model_name="dailylog",
            name="cardio",
        ),
        migrations.AddField(
            model_name="dailylog",
            name="fibre",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="workout_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("weight_training", "Weight Training"),
                    ("cardio", "Cardio"),
                    ("bodyweight_training", "Bodyweight Training"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="CustomMetricEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "daily_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_entries",
                        to="logs.dailylog",
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="logs.custommetricdefinition",
                    ),
                ),
            ],
            options={
                "db_table": "custom_metric_entries",
                "unique_together": {("definition", "daily_log")},
            },
        ),
    ]
