# Generated by Django 4.2.28 on 2026-02-14 04:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MonthlyMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("month", models.DateField(help_text="First day of the month")),
                (
                    "avg_weight",
                    models.DecimalField(decimal_places=1, max_digits=5, null=True),
                ),
                ("bmi", models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                (
                    "bmi_category",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "weight_change",
                    models.DecimalField(decimal_places=1, max_digits=5, null=True),
                ),
                ("consistency_score", models.IntegerField(default=0)),
                ("days_logged", models.IntegerField(default=0)),
                ("protein_hit_days", models.IntegerField(default=0)),
                ("workout_days", models.IntegerField(default=0)),
                ("total_days_in_month", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "monthly_metrics",
                "ordering": ["-month"],
            },
        ),
    ]
