# Generated by Django 4.2.28 on 2026-02-14 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboard", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlymetrics",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monthly_metrics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="monthlymetrics",
            index=models.Index(
                fields=["user", "month"], name="idx_monthly_metrics_user_month"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="monthlymetrics",
            unique_together={("user", "month")},
        ),
    ]
