# Generated by Django 4.2.28 on 2026-02-25 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertarget",
            name="carbs_target",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usertarget",
            name="fats_target",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usertarget",
            name="fibre_target",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usertarget",
            name="sleep_target",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="usertarget",
            name="steps_target",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usertarget",
            name="water_target",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="diet_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Vegetarian", "Vegetarian"),
                    ("Non-Vegetarian", "Non-Vegetarian"),
                    ("Vegan", "Vegan"),
                    ("Eggetarian", "Eggetarian"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
