# Generated by Django 4.2.28 on 2026-02-14 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("measurements", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bodymeasurement",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="measurements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="bodymeasurement",
            index=models.Index(fields=["user", "date"], name="idx_body_meas_user_date"),
        ),
        migrations.AlterUniqueTogether(
            name="bodymeasurement",
            unique_together={("user", "date")},
        ),
    ]
