# Generated by Django 4.2.28 on 2026-02-25 18:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("logs", "0003_custommetricdefinition_remove_dailylog_cardio_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("grain", "Grain"),
                            ("protein_source", "Protein Source"),
                            ("vegetable", "Vegetable"),
                            ("fruit", "Fruit"),
                            ("dairy", "Dairy"),
                            ("snack", "Snack"),
                            ("beverage", "Beverage"),
                            ("condiment", "Condiment"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "diet_type",
                    models.CharField(
                        choices=[
                            ("vegetarian", "Vegetarian"),
                            ("non_vegetarian", "Non-Vegetarian"),
                            ("vegan", "Vegan"),
                            ("eggetarian", "Eggetarian"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "calories_per_100g",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "protein_per_100g",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "carbs_per_100g",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "fats_per_100g",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "fibre_per_100g",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_custom", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_foods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "foods",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FoodEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("snack", "Snack"),
                            ("dinner", "Dinner"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantity_grams",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0.1)],
                    ),
                ),
                ("calories", models.PositiveIntegerField(default=0)),
                (
                    "protein",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                (
                    "carbs",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                (
                    "fats",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                (
                    "fibre",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "daily_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_entries",
                        to="logs.dailylog",
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="foods.food",
                    ),
                ),
            ],
            options={
                "db_table": "food_entries",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["daily_log", "meal_type"],
                        name="idx_food_entries_log_meal",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="food",
            index=models.Index(fields=["name"], name="idx_foods_name"),
        ),
        migrations.AddIndex(
            model_name="food",
            index=models.Index(fields=["diet_type"], name="idx_foods_diet_type"),
        ),
        migrations.AddIndex(
            model_name="food",
            index=models.Index(fields=["created_by"], name="idx_foods_created_by"),
        ),
    ]
